In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [24]:
# Load the Dataset
data = pd.read_csv("./Churn_Modelling.csv")
data.head()

   RowNumber  CustomerId   Surname  CreditScore  ... HasCrCard IsActiveMember  EstimatedSalary  Exited
0          1    15634602  Hargrave          619  ...         1              1        101348.88       1
1          2    15647311      Hill          608  ...         0              1        112542.58       0
2          3    15619304      Onio          502  ...         1              0        113931.57       1
3          4    15701354      Boni          699  ...         0              0         93826.63       0
4          5    15737888  Mitchell          850  ...         1              1         79084.10       0

[5 rows x 14 columns]

In [25]:
# Preprocess the Data
## Drop Irrelevat Features
data = data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data.head()

   CreditScore Geography  Gender  Age  Tenure  ...  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female   42       2  ...              1          1               1        101348.88       1
1          608     Spain  Female   41       1  ...              1          0               1        112542.58       0
2          502    France  Female   42       8  ...              3          1               0        113931.57       1
3          699    France  Female   39       1  ...              2          0               0         93826.63       0
4          850     Spain  Female   43       2  ...              1          1               1         79084.10       0

[5 rows x 11 columns]

In [26]:
# Encode Categorical Variables

label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data.head()

   CreditScore Geography  Gender  Age  Tenure  ...  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited
0          619    France       0   42       2  ...              1          1               1        101348.88       1
1          608     Spain       0   41       1  ...              1          0               1        112542.58       0
2          502    France       0   42       8  ...              3          1               0        113931.57       1
3          699    France       0   39       1  ...              2          0               0         93826.63       0
4          850     Spain       0   43       2  ...              1          1               1         79084.10       0

[5 rows x 11 columns]

In [27]:
## One hot Encode 'Geography'
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_goe=OneHotEncoder(sparse_output=False)
geo_encoder = onehot_encoder_goe.fit_transform(data[['Geography']])
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [28]:
onehot_encoder_goe.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [29]:
geo_encoded_df = pd.DataFrame(geo_encoder,columns=onehot_encoder_goe.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [30]:
# Combine One hot Encoded Columns with the original Data
data = pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

   CreditScore  Gender  Age  Tenure  ...  Exited  Geography_France  Geography_Germany  Geography_Spain
0          619       0   42       2  ...       1               1.0                0.0              0.0
1          608       0   41       1  ...       0               0.0                0.0              1.0
2          502       0   42       8  ...       1               1.0                0.0              0.0
3          699       0   39       1  ...       0               1.0                0.0              0.0
4          850       0   43       2  ...       0               0.0                0.0              1.0

[5 rows x 13 columns]

In [31]:
## Save the Encoders and Scaler
with open('label_encoder_gemder.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)
    
with open('label_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_goe,file)

In [33]:
## Devide the Dataset into Independent and Dependent features

X = data.drop('Exited',axis=1);
y= data['Exited']

# Split the data into Training and Testing Set
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [34]:
# Scale these Features

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [35]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

## ANN Implementation

In [41]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [42]:
## Build our ANN Model

model = Sequential([
    Input(shape=(X_train.shape[1],)),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

In [43]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                      │ (None, 64)                  │             832 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [45]:
## Optimzer

opt = tf.keras.optimizers.Adam(learning_rate=0.01)

In [46]:
## COmpile the model

model.compile(optimizer=opt,loss="binary_crossentropy",metrics=["accuracy"])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [47]:
## Setup the tensorBoard

log_dir = "logs/fit" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

tensorbiard_callback = TensorBoard(log_dir=log_dir,histogram_freq=1)

In [48]:
## SetUp Early Stopping

ealy_stopping = EarlyStopping(monitor='val_loss',patience=8,restore_best_weights=True)

In [49]:
## Train the Model

history = model.fit(
    X_train,y_train, validation_data=(X_test,y_test), epochs=100,
    callbacks=[tensorbiard_callback,ealy_stopping]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.8375 - loss: 0.3946 - val_accuracy: 0.8385 - val_loss: 0.3941
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8541 - loss: 0.3592 - val_accuracy: 0.8555 - val_loss: 0.3468
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8565 - loss: 0.3516 - val_accuracy: 0.8635 - val_loss: 0.3391
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8604 - loss: 0.3430 - val_accuracy: 0.8610 - val_loss: 0.3517
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8604 - loss: 0.3400 - val_accuracy: 0.8635 - val_loss: 0.3378
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8602 - loss: 0.3375 - val_accuracy: 0.8580 - val_loss: 0.3440
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8633 - loss: 0.3352 - val_accuracy: 0.8580 - val_loss: 0.3440
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8630 - loss: 0.3363 - val_accuracy: 0.8630 - val_loss: 0.3452
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8621 - loss: 0.3314 - val_accuracy: 0.8580 - val_loss: 0.3367
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8637 - loss: 0.3297 - val_accuracy: 0.8555 - val_loss: 0.3486
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8654 - loss: 0.3276 - val_accuracy: 0.8620 - val_loss: 0.3511
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8662 - loss: 0.3265 - val_accuracy: 0.8525 - val_loss: 0.3631
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8670 - loss: 0.3247 - val_accuracy: 0.8535 - val_loss: 0.3665
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8687 - loss: 0.3205 - val_accuracy: 0.8520 - val_loss: 0.3607
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8685 - loss: 0.3236 - val_accuracy: 0.8565 - val_loss: 0.3455
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8705 - loss: 0.3183 - val_accuracy: 0.8505 - val_loss: 0.3643
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8684 - loss: 0.3202 - val_accuracy: 0.8550 - val_loss: 0.3596

In [50]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [52]:
## Load TensorBoard Extension

%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [55]:
%tensorboard --logdir logs/fit20260409-030354